app/urls.py
from django.urls import path
from app.views import *
app_name='app'
urlpatterns=[
    path('dvs/',dvs,name='dvs')
]

app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('bike/',bike,name='bike')
]

project12/urls.py
from django.contrib import admin
from django.urls import path,include
import app
import app1

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/',include('app.urls')),
    path('app1/',include('app1.urls')),
]

app/models.py
from django.db import models

# Create your models here.

app1/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render

# Create your views here.
def dvs(request):
    return render(request,'dvs.html')

app1/views.py
from django.shortcuts import render

# Create your views here.
def bike(request):
    return render(request,'bike.html')

templates/bike.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
    <li>meteor 650</li>
    <li>interceptor</li>
    <li>classic</li>
    </ul>
    <h2><a href="{% url 'app:dvs' %}">click here</a></h2>
</body>
</html>

templates/dvs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>royal enfield</h1>
    <h2><a href="{% url 'app1:bike' %}">click here</a></h2>
</body>
</html>